language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script:
  - phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
